#!/bin/bash

DATA_FILE="./vault/data/file_sizes.yml"
IMAGE_DIR="./assets/images"

echo "Generating file sizes to $DATA_FILE..."
echo "# Automatically generated by scripts/generate_file_sizes.sh" > "$DATA_FILE"

# Find all files in assets/images, excluding tiles directories (which are huge)
# We only care about PNG, PDF, SVG, and the main images.
find "$IMAGE_DIR" -type f \( -name "*.png" -o -name "*.pdf" -o -name "*.svg" -o -name "*.webp" \) -not -path "*/tiles/*" -not -path "*/tiles-dark/*" | while read -r file; do
    # Get relative path from assets/images
    rel_path=${file#$IMAGE_DIR/}
    # Get size in bytes
    size_bytes=$(stat -c%s "$file")
    # Convert to MB with 2 decimal places
    size_mb=$(awk "BEGIN {printf \"%.2f\", $size_bytes / 1048576}")
    
    # Escape path for YAML key if needed (though these paths should be simple)
    echo "'$rel_path': '$size_mb MB'" >> "$DATA_FILE"
done

echo "Done."
